
server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: flow-manager-route
          uri: lb://Flow_manager
          predicates:
            - Path=api/v1/flow_manager/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
